"""Lightweight stubs — avoids Pyright scanning the full ccxt package."""

from typing import Any

def binance(config: dict[str, Any]) -> Any: ...
def bybit(config: dict[str, Any]) -> Any: ...
def okx(config: dict[str, Any]) -> Any: ...
def hyperliquid(config: dict[str, Any]) -> Any: ...
