from collections.abc import Awaitable, Callable
from typing import Any, TypeVar

_T = TypeVar("_T")

class TelegramClient:
    def __init__(self, session: str | Any, api_id: int, api_hash: str, **kwargs: Any) -> None: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def is_user_authorized(self) -> bool: ...
    async def start(
        self,
        phone: str | Callable[[], str] | None = ...,
        code_callback: Callable[[], str] | None = ...,
        password: Callable[[], str] | str | None = ...,
        **kwargs: Any,
    ) -> None: ...
    async def send_code_request(self, phone: str, **kwargs: Any) -> Any: ...
    async def sign_in(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_me(self) -> Any: ...
    async def run_until_disconnected(self) -> None: ...
    def on(self, event: Any) -> Callable[[Callable[..., Awaitable[Any]]], Callable[..., Awaitable[Any]]]: ...
    def iter_messages(self, entity: Any, **kwargs: Any) -> Any: ...

class events:
    class NewMessage:
        def __init__(self, chats: Any = None, **kwargs: Any) -> None: ...
