-- Crypto Trading System - Initial Schema
-- Run in Supabase SQL Editor or via CLI

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS vector;

-- Signals generated by strategy engine
CREATE TABLE IF NOT EXISTS signals (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  symbol VARCHAR(20) NOT NULL,
  direction VARCHAR(10) NOT NULL CHECK (direction IN ('BUY', 'SELL', 'IGNORE')),
  confidence INTEGER NOT NULL CHECK (confidence >= 0 AND confidence <= 100),
  entry_price DECIMAL(20, 8),
  stop_loss DECIMAL(20, 8),
  tp1 DECIMAL(20, 8),
  tp2 DECIMAL(20, 8),
  tp3 DECIMAL(20, 8),
  reasons JSONB NOT NULL DEFAULT '{}',
  mtf_status JSONB NOT NULL DEFAULT '{}',
  timeframe_entry VARCHAR(10) DEFAULT '5m',
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'accepted', 'skipped', 'expired')),
  telegram_message_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ
);

CREATE INDEX idx_signals_symbol ON signals(symbol);
CREATE INDEX idx_signals_status ON signals(status);
CREATE INDEX idx_signals_created ON signals(created_at DESC);

-- Executed trades
CREATE TABLE IF NOT EXISTS trades (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  signal_id UUID REFERENCES signals(id),
  symbol VARCHAR(20) NOT NULL,
  direction VARCHAR(10) NOT NULL CHECK (direction IN ('LONG', 'SHORT')),
  entry_price DECIMAL(20, 8) NOT NULL,
  quantity DECIMAL(20, 8) NOT NULL,
  stop_loss DECIMAL(20, 8) NOT NULL,
  tp1 DECIMAL(20, 8),
  tp2 DECIMAL(20, 8),
  tp3 DECIMAL(20, 8),
  tp1_hit BOOLEAN DEFAULT FALSE,
  tp2_hit BOOLEAN DEFAULT FALSE,
  tp3_hit BOOLEAN DEFAULT FALSE,
  sl_moved_breakeven BOOLEAN DEFAULT FALSE,
  sl_locked_1r BOOLEAN DEFAULT FALSE,
  exit_price DECIMAL(20, 8),
  pnl DECIMAL(20, 8),
  pnl_percent DECIMAL(10, 4),
  r_multiple DECIMAL(10, 4),
  status VARCHAR(20) DEFAULT 'open' CHECK (status IN ('open', 'partial', 'closed', 'stopped', 'liquidated')),
  close_reason VARCHAR(50),
  binance_order_id VARCHAR(50),
  binance_sl_order_id VARCHAR(50),
  risk_amount DECIMAL(20, 8),
  lesson TEXT,
  opened_at TIMESTAMPTZ DEFAULT NOW(),
  closed_at TIMESTAMPTZ
);

CREATE INDEX idx_trades_symbol ON trades(symbol);
CREATE INDEX idx_trades_status ON trades(status);
CREATE INDEX idx_trades_opened ON trades(opened_at DESC);

-- Balance snapshots
CREATE TABLE IF NOT EXISTS balances (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  total_balance DECIMAL(20, 8) NOT NULL,
  available_balance DECIMAL(20, 8) NOT NULL,
  unrealized_pnl DECIMAL(20, 8) DEFAULT 0,
  daily_pnl DECIMAL(20, 8) DEFAULT 0,
  daily_trades_count INTEGER DEFAULT 0,
  snapshot_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(snapshot_date)
);

-- System logs
CREATE TABLE IF NOT EXISTS logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  level VARCHAR(10) NOT NULL CHECK (level IN ('info', 'warn', 'error', 'trade', 'signal')),
  source VARCHAR(50) NOT NULL,
  message TEXT NOT NULL,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_logs_level ON logs(level);
CREATE INDEX idx_logs_created ON logs(created_at DESC);

-- Performance metrics (daily rollup)
CREATE TABLE IF NOT EXISTS performance_metrics (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  metric_date DATE NOT NULL DEFAULT CURRENT_DATE,
  total_trades INTEGER DEFAULT 0,
  winning_trades INTEGER DEFAULT 0,
  losing_trades INTEGER DEFAULT 0,
  win_rate DECIMAL(5, 2),
  total_pnl DECIMAL(20, 8) DEFAULT 0,
  avg_r_multiple DECIMAL(10, 4),
  max_drawdown DECIMAL(10, 4),
  best_pair VARCHAR(20),
  worst_pair VARCHAR(20),
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(metric_date)
);

-- Per-pair strategy effectiveness
CREATE TABLE IF NOT EXISTS pair_stats (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  symbol VARCHAR(20) NOT NULL UNIQUE,
  total_signals INTEGER DEFAULT 0,
  total_trades INTEGER DEFAULT 0,
  wins INTEGER DEFAULT 0,
  losses INTEGER DEFAULT 0,
  win_rate DECIMAL(5, 2) DEFAULT 0,
  avg_r_multiple DECIMAL(10, 4) DEFAULT 0,
  strategy_score DECIMAL(5, 2) DEFAULT 50,
  last_trade_at TIMESTAMPTZ,
  notes TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- AI trade lessons with embeddings
CREATE TABLE IF NOT EXISTS trade_lessons (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  trade_id UUID REFERENCES trades(id),
  symbol VARCHAR(20) NOT NULL,
  direction VARCHAR(10) NOT NULL,
  outcome VARCHAR(10) CHECK (outcome IN ('win', 'loss', 'breakeven')),
  setup_description TEXT NOT NULL,
  lesson_text TEXT NOT NULL,
  tags TEXT[] DEFAULT '{}',
  embedding vector(768),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_trade_lessons_symbol ON trade_lessons(symbol);

-- Seed top 20 pairs
INSERT INTO pair_stats (symbol) VALUES
  ('BTCUSDT'), ('ETHUSDT'), ('BNBUSDT'), ('SOLUSDT'), ('XRPUSDT'),
  ('ADAUSDT'), ('DOGEUSDT'), ('AVAXUSDT'), ('DOTUSDT'), ('LINKUSDT'),
  ('MATICUSDT'), ('LTCUSDT'), ('UNIUSDT'), ('ATOMUSDT'), ('ETCUSDT'),
  ('FILUSDT'), ('NEARUSDT'), ('APTUSDT'), ('ARBUSDT'), ('OPUSDT')
ON CONFLICT (symbol) DO NOTHING;

-- Row Level Security (enable when using auth)
ALTER TABLE signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE performance_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE pair_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE trade_lessons ENABLE ROW LEVEL SECURITY;

-- Service role bypass policies (adjust for your auth setup)
CREATE POLICY "Service full access signals" ON signals FOR ALL USING (true);
CREATE POLICY "Service full access trades" ON trades FOR ALL USING (true);
CREATE POLICY "Service full access balances" ON balances FOR ALL USING (true);
CREATE POLICY "Service full access logs" ON logs FOR ALL USING (true);
CREATE POLICY "Service full access metrics" ON performance_metrics FOR ALL USING (true);
CREATE POLICY "Service full access pair_stats" ON pair_stats FOR ALL USING (true);
CREATE POLICY "Service full access trade_lessons" ON trade_lessons FOR ALL USING (true);
